# coding: utf-8

"""
    Looker API 3.0 Reference

    ### Authorization  The Looker API uses Looker **API3** credentials for authorization and access control. Looker admins can create API3 credentials on Looker's **Admin/Users** page. Pass API3 credentials to the **/login** endpoint to obtain a temporary access_token. Include that access_token in the Authorization header of Looker API requests. For details, see [Looker API Authorization](https://looker.com/docs/r/api/authorization)  ### Client SDKs  The Looker API is a RESTful system that should be usable by any programming language capable of making HTTPS requests. Client SDKs for a variety of programming languages can be generated from the Looker API's Swagger JSON metadata to streamline use of the Looker API in your applications. A client SDK for Ruby is available as an example. For more information, see [Looker API Client SDKs](https://looker.com/docs/r/api/client_sdks)  ### Try It Out!  The 'api-docs' page served by the Looker instance includes 'Try It Out!' buttons for each API method. After logging in with API3 credentials, you can use the \"Try It Out!\" buttons to call the API directly from the documentation page to interactively explore API features and responses.  ### Versioning  Future releases of Looker will expand this API release-by-release to securely expose more and more of the core power of Looker to API client applications. API endpoints marked as \"beta\" may receive breaking changes without warning. Stable (non-beta) API endpoints should not receive breaking changes in future releases. For more information, see [Looker API Versioning](https://looker.com/docs/r/api/versioning) 

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_attribute_api import UserAttributeApi


class TestUserAttributeApi(unittest.TestCase):
    """ UserAttributeApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_attribute_api.UserAttributeApi()

    def tearDown(self):
        pass

    def test_all_user_attribute_group_values(self):
        """
        Test case for all_user_attribute_group_values

        Get User Attribute Group Values
        """
        pass

    def test_all_user_attributes(self):
        """
        Test case for all_user_attributes

        Get All User Attributes
        """
        pass

    def test_create_user_attribute(self):
        """
        Test case for create_user_attribute

        Create User Attribute
        """
        pass

    def test_delete_user_attribute(self):
        """
        Test case for delete_user_attribute

        Delete User Attribute
        """
        pass

    def test_set_user_attribute_group_values(self):
        """
        Test case for set_user_attribute_group_values

        Set User Attribute Group Values
        """
        pass

    def test_update_user_attribute(self):
        """
        Test case for update_user_attribute

        Update User Attribute
        """
        pass

    def test_user_attribute(self):
        """
        Test case for user_attribute

        Get User Attribute
        """
        pass


if __name__ == '__main__':
    unittest.main()
